sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily Generator Production"
    id: daily_generator_production
    register_type: holding
    address: 536
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:generator-portable"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total Generator Production"
    id: total_generator_production
    register_type: holding
    address: 537
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator L1 Voltage"
    id: generator_l1_voltage
    register_type: holding
    address: 661
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator L2 Voltage"
    id: generator_l2_voltage
    register_type: holding
    address: 662
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator L3 Voltage"
    id: generator_l3_voltage
    register_type: holding
    address: 663
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator L1 Power"
    register_type: holding
    address: 664
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator L2 Power"
    register_type: holding
    address: 665
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator L3 Power"
    register_type: holding
    address: 666
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Power Total"
    id: generator_power_total
    register_type: holding
    address: 667
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "AC Generator Relay" # bit 3
    register_type: holding
    address: 552
    bitmask: 0x8
    device_class: power
    icon: "mdi:generator-stationary"

select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Port Use"
    address: 133
    value_type: U_WORD
    entity_category: config
    icon: "mdi:connection"
    optionsmap:
      "Generator Input": 0
      "SmartLoad Output": 1
      "Micro Inverter Input": 2

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator"
    register_type: holding
    address: 132
    bitmask: 1
    entity_category: config
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Microinverter Export Cut-off"
    register_type: holding
    address: 178
    bitmask: 0x0001 # bit 0
    entity_category: config
    icon: "mdi:solar-panel"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Peak Shaving Enable"
    register_type: holding
    address: 178
    bitmask: 0x0004 # bit 2
    entity_category: config
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator On-Grid Always On"
    register_type: holding
    address: 178
    bitmask: 0x0040 # bit 6
    entity_category: config
    icon: "mdi:generator-stationary"

number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "SmartLoad Off Voltage"
    address: 134
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 38
    max_value: 63
    step: 0.01
    entity_category: config
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "SmartLoad Off SOC"
    address: 135
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    entity_category: config
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "SmartLoad On Voltage"
    address: 136
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 38
    max_value: 63
    step: 0.01
    entity_category: config
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "SmartLoad On SOC"
    address: 137
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    entity_category: config
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Operating Time"
    address: 121
    unit_of_measurement: "h"
    device_class: duration
    value_type: U_WORD
    multiply: 10
    min_value: 0
    max_value: 24
    step: 1
    entity_category: config
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Cooling Time"
    address: 122
    unit_of_measurement: "h"
    device_class: duration
    value_type: U_WORD
    multiply: 10
    min_value: 0
    max_value: 24
    step: 1
    entity_category: config
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "PV Minimum Power To Start Generator"
    address: 139
    unit_of_measurement: "W"
    device_class: power
    min_value: 0
    max_value: 8000
    step: 1
    value_type: U_WORD
    entity_category: config
    disabled_by_default: true
    icon: "mdi:solar-power-variant"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Peak Shaving Power"
    id: generator_peak_shaving_power
    register_type: holding
    address: 190
    unit_of_measurement: "W"
    device_class: power
    value_type: U_WORD
    min_value: 0
    step: 1
    entity_category: config
    icon: "mdi:generator-stationary"
