substitutions:
  name: deye-inverter
  friendly_name: "Deye Inverter"
  device_description: "Deye Inverter SG0XLP3"
  modbus_controller_id: deye_modbus_controller
  # Safe Mode Default parameters
  default_maximum_battery_charge_current: "140" # Amps
  default_max_sell_power: "12000" # Watts
  default_system_work_mode: "Zero Export To Load" # "Selling First", "Zero Export To Load", "Zero Export To CT"
  default_solar_sell: "on" # "on", "off"

packages:
  init: !include packages/init.yaml
  battery: !include packages/deye_hybrid_3p/battery.yaml
  gen: !include packages/deye_hybrid_3p/gen.yaml
  grid: !include packages/deye_hybrid_3p/grid.yaml
  load: !include packages/deye_hybrid_3p/load.yaml
  work_mode: !include packages/deye_hybrid_3p/work_mode.yaml
  device: !include packages/deye_hybrid_3p/device.yaml
  inverter: !include packages/deye_hybrid_3p/inverter.yaml
  pv: !include packages/deye_hybrid_3p/pv.yaml
  tou: !include packages/deye_hybrid_3p/tou.yaml

script:
  - id: set_safe_modbus_registers
    then:
      - logger.log:
          level: INFO
          format: "Setting safe Modbus register values"
      - number.set:
          id: maximum_battery_charge_current
          value: ${default_maximum_battery_charge_current}
      - number.set:
          id: max_sell_power
          value: ${default_max_sell_power}
      - select.set:
          id: system_work_mode
          option: ${default_system_work_mode}
      - switch.turn_${default_solar_sell}:
          id: switch_solar_sell
